### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by HakaCode** [craftygg/translations#49]
Would you be able to contribute with the translation into Portuguese?

**Comment by treboryx** [comment]
Contributions are made by the community through https://crowdin.com/project/crafty

I've added Portuguese in the list, feel free to contribute!

**Comment by HakaCode** [comment]
> As contribuições são feitas pela comunidade em https://crowdin.com/project/crafty
> 
> Adicionei o português na lista, fique à vontade para contribuir!

could add brazilian portuguese, please.
some terms in pt_PT(portugal) came out different from **pt_BR** (**portuguese (Brazil)**)

**Comment by treboryx** [comment]
Added!
